{
 "title": "Battery",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Live Battery State of Charge (kWh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /battery_capacity/\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Historical Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"powersim3.0\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /battery_charge|battery_discharge|battery_capacity/)\r\n  |> filter(fn: (r) => r[\"url\"] == \"http://powersim:3001/api\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n"
    }
   ]
  },
  {
   "title": "Live Battery Discharge Rate (kW)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /battery_discharge/\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Actual Battery Charge/Discharge vs. Forecasted Charge/Discharge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "load =\r\n  from(bucket: \"forecast\")\r\n    |> range(start: v.timeRangeStart, stop: now())\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_load_series\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"PredictedValue\")\r\n    |> filter(fn: (r) => r[\"model\"] == \"live_combined_v1\")\r\n    |> filter(fn: (r) => r[\"horizon\"] == \"1h\")\r\n    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n    |> set(key: \"series_name\", value: \"Forecasted Load\")\r\n\r\ngen =\r\n  from(bucket: \"forecast\")\r\n    |> range(start: v.timeRangeStart, stop: now())\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_total_renewable_series\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"PredictedValue\")\r\n    |> filter(fn: (r) => r[\"model\"] == \"live_combined_v1\")\r\n    |> filter(fn: (r) => r[\"horizon\"] == \"1h\")\r\n    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n    |> set(key: \"series_name\", value: \"Forecasted Generation\")\r\n\r\ndiff =\r\n  join(tables: {load: load, gen: gen}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        _value: if r._value_gen - r._value_load > 2000.0 then 2000.0\r\n          else if r._value_gen - r._value_load < -2000.0 then -2000.0\r\n          else r._value_gen - r._value_load,\r\n        _field: \"Forecasted Battery\"\r\n    }))\r\n\r\nmerged =\r\n  from(bucket: \"simulations\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      (r._field == \"battery_discharge\" or r._field == \"battery_charge\") and\r\n      r.url == \"http://powersim:3001/api\"\r\n    )\r\n    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n    |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        _value:\r\n          (if exists r.battery_charge then r.battery_charge else 0.0)\r\n          +\r\n          (if exists r.battery_discharge then -1.0 * r.battery_discharge else 0.0),\r\n        _field: \"Actual Battery\"\r\n    }))\r\n\r\nunion(tables: [\r\n  diff |> group(columns: [\"_field\"]),\r\n  merged |> group(columns: [\"_field\"])\r\n])"
    }
   ]
  },
  {
   "title": "Live Battery Charge Rate (kW)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /battery_charge/\r\n  )\r\n  |> last()"
    }
   ]
  }
 ]
}