{
 "title": "Loads",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average Load (Selected timeframe)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /load/\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> mean()\r\n  |> keep(columns: [\"_field\", \"_value\"])\r\n  |> rename(columns: {_field: \"field\", _value: \"value\"})"
    }
   ]
  },
  {
   "title": "Historical Load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"powersim3.0\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /load/)\r\n  |> filter(fn: (r) => r[\"url\"] == \"http://powersim:3001/api\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n"
    }
   ]
  },
  {
   "title": "Average Load (Past 2h)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /load/\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> mean()\r\n  |> keep(columns: [\"_field\", \"_value\"])\r\n  |> rename(columns: {_field: \"field\", _value: \"value\"})"
    }
   ]
  },
  {
   "title": "Average Load (Past 24h)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"simulations\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n      r.source == \"powersim3.0\" and\r\n      r._field =~ /load/\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> mean()\r\n  |> keep(columns: [\"_field\", \"_value\"])\r\n  |> rename(columns: {_field: \"field\", _value: \"value\"})"
    }
   ]
  },
  {
   "title": "Actual Load vs. Forecasted Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "actual = from(bucket: \"simulations\")\r\n  |> range(start: v.timeRangeStart, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"powersim3.0\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"http://powersim:3001/api\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n  |> set(key: \"series_name\", value: \"Actual Load\")\r\n\r\nforecast = from(bucket: \"forecast\")\r\n  |> range(start: v.timeRangeStart, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forecast_load_series\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PredictedValue\")\r\n  |> filter(fn: (r) => r[\"model\"] == \"live_combined_v1\")\r\n  |> filter(fn: (r) => r[\"horizon\"] == \"1h\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false, timeSrc: \"_start\")\r\n  |> set(key: \"series_name\", value: \"Forecasted Load\")\r\n\r\nunion(tables: [actual, forecast])\r\n  |> keep(columns: [\"_time\", \"_value\", \"series_name\"])\r\n  |> group(columns: [\"series_name\"])"
    }
   ]
  }
 ]
}